notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+/

language: node_js

node_js:
  - 10
  - 12

install:
  - yarn install --frozen-lockfile --non-interactive

jobs:
  include:
    - &checkTs
      stage: Check TypeScript
      script:
        - yarn check:types
    - <<: *checkTs
      node_js: 12
    - &lint
      stage: Lint
      script:
        - yarn lint
    - <<: *lint
      node_js: 12
    - &checkFormatting
      stage: Check Formatting
      script:
        - yarn check:format
    - <<: *checkFormatting
      node_js: 12
    - &build
      stage: Build
      script:
        - yarn build
    - <<: *build
      node_js: 12
